export type WwwMode = "keep" | "www" | "non-www";
export type CacheProfile = "none" | "basic" | "aggressive";

export type RedirectRule = {
  from: string;
  to: string;
  status: "301" | "302";
};

export type HtaccessGeneratorState = {
  forceHttps: boolean;
  wwwMode: WwwMode;
  enableWordPress: boolean;
  disableDirectoryListing: boolean;
  protectDotFiles: boolean;
  blockXmlRpc: boolean;
  enableCompression: boolean;
  cacheProfile: CacheProfile;
  securityHeaders: boolean;
  corsOrigins: string;
  hotlinkProtection: boolean;
  allowedHotlinkDomains: string;
  redirects: RedirectRule[];
};

export const defaultHtaccessState: HtaccessGeneratorState = {
  forceHttps: true,
  wwwMode: "keep",
  enableWordPress: true,
  disableDirectoryListing: true,
  protectDotFiles: true,
  blockXmlRpc: false,
  enableCompression: true,
  cacheProfile: "basic",
  securityHeaders: true,
  corsOrigins: "",
  hotlinkProtection: false,
  allowedHotlinkDomains: "",
  redirects: [{ from: "/old-page", to: "/new-page", status: "301" }]
};

export function buildHtaccess(state: HtaccessGeneratorState) {
  const sections = [
    "# Generated by DevStack Tools",
    buildRewriteSection(state),
    buildSecuritySection(state),
    buildCompressionSection(state),
    buildCacheSection(state),
    buildCorsSection(state)
  ].filter(Boolean);

  return `${sections.join("\n\n")}\n`;
}

export function validateHtaccessState(state: HtaccessGeneratorState) {
  const warnings: string[] = [];

  if (state.wwwMode !== "keep") {
    warnings.push("Las reglas www/no-www usan HTTP_HOST. Pruebalas en staging si tienes subdominios.");
  }

  if (state.blockXmlRpc) {
    warnings.push("Bloquear xmlrpc.php puede afectar apps moviles, Jetpack o integraciones antiguas de WordPress.");
  }

  if (state.hotlinkProtection && !splitValues(state.allowedHotlinkDomains).length) {
    warnings.push("La proteccion hotlink necesita al menos un dominio permitido.");
  }

  if (state.corsOrigins.trim() === "*") {
    warnings.push("CORS con * permite cualquier origen. Usalo solo en assets publicos.");
  }

  if (state.redirects.some((redirect) => !redirect.from.trim() || !redirect.to.trim())) {
    warnings.push("Hay redirecciones incompletas. Rellena origen y destino o elimina la regla.");
  }

  return warnings;
}

function buildRewriteSection(state: HtaccessGeneratorState) {
  const lines = ["<IfModule mod_rewrite.c>", "  RewriteEngine On"];

  if (state.forceHttps) {
    lines.push("", "  # Force HTTPS", "  RewriteCond %{HTTPS} !=on", "  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
  }

  if (state.wwwMode === "www") {
    lines.push("", "  # Force www", "  RewriteCond %{HTTP_HOST} !^www\\. [NC]", "  RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
  }

  if (state.wwwMode === "non-www") {
    lines.push("", "  # Remove www", "  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]", "  RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
  }

  const redirects = state.redirects.filter((redirect) => redirect.from.trim() && redirect.to.trim());

  if (redirects.length) {
    lines.push("", "  # Custom redirects");
    redirects.forEach((redirect) => {
      lines.push(`  Redirect ${redirect.status} ${normalizePath(redirect.from)} ${redirect.to.trim()}`);
    });
  }

  if (state.hotlinkProtection) {
    const domains = splitValues(state.allowedHotlinkDomains);

    if (domains.length) {
      lines.push("", "  # Prevent image hotlinking", "  RewriteCond %{HTTP_REFERER} !^$");
      domains.forEach((domain) => {
        lines.push(`  RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${escapeRewriteDomain(domain)}(/|$) [NC]`);
      });
      lines.push("  RewriteRule \\.(jpe?g|png|gif|webp|svg)$ - [F,L,NC]");
    }
  }

  if (state.enableWordPress) {
    lines.push(
      "",
      "  # WordPress pretty permalinks",
      "  RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]",
      "  RewriteBase /",
      "  RewriteRule ^index\\.php$ - [L]",
      "  RewriteCond %{REQUEST_FILENAME} !-f",
      "  RewriteCond %{REQUEST_FILENAME} !-d",
      "  RewriteRule . /index.php [L]"
    );
  }

  lines.push("</IfModule>");
  return lines.join("\n");
}

function buildSecuritySection(state: HtaccessGeneratorState) {
  const lines: string[] = [];

  if (state.disableDirectoryListing) {
    lines.push("# Disable directory listing", "Options -Indexes");
  }

  if (state.protectDotFiles) {
    lines.push(
      "",
      "# Protect hidden files",
      "<FilesMatch \"^\\.\">",
      "  Require all denied",
      "</FilesMatch>"
    );
  }

  if (state.blockXmlRpc) {
    lines.push("", "# Block WordPress XML-RPC", "<Files xmlrpc.php>", "  Require all denied", "</Files>");
  }

  if (state.securityHeaders) {
    lines.push(
      "",
      "<IfModule mod_headers.c>",
      "  Header always set X-Content-Type-Options \"nosniff\"",
      "  Header always set X-Frame-Options \"SAMEORIGIN\"",
      "  Header always set Referrer-Policy \"strict-origin-when-cross-origin\"",
      "  Header always set Permissions-Policy \"camera=(), microphone=(), geolocation=()\"",
      "</IfModule>"
    );
  }

  return lines.join("\n").trim();
}

function buildCompressionSection(state: HtaccessGeneratorState) {
  if (!state.enableCompression) {
    return "";
  }

  return [
    "<IfModule mod_deflate.c>",
    "  AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css text/javascript application/javascript application/json application/xml image/svg+xml",
    "</IfModule>"
  ].join("\n");
}

function buildCacheSection(state: HtaccessGeneratorState) {
  if (state.cacheProfile === "none") {
    return "";
  }

  const imageMaxAge = state.cacheProfile === "aggressive" ? "31536000" : "2592000";
  const assetMaxAge = state.cacheProfile === "aggressive" ? "31536000" : "604800";

  return [
    "<IfModule mod_expires.c>",
    "  ExpiresActive On",
    `  ExpiresByType image/jpeg "access plus ${Math.round(Number(imageMaxAge) / 86400)} days"`,
    `  ExpiresByType image/png "access plus ${Math.round(Number(imageMaxAge) / 86400)} days"`,
    `  ExpiresByType image/webp "access plus ${Math.round(Number(imageMaxAge) / 86400)} days"`,
    `  ExpiresByType image/svg+xml "access plus ${Math.round(Number(imageMaxAge) / 86400)} days"`,
    `  ExpiresByType text/css "access plus ${Math.round(Number(assetMaxAge) / 86400)} days"`,
    `  ExpiresByType application/javascript "access plus ${Math.round(Number(assetMaxAge) / 86400)} days"`,
    "</IfModule>",
    "",
    "<IfModule mod_headers.c>",
    `  <FilesMatch "\\.(jpg|jpeg|png|gif|webp|svg|css|js|woff2?)$">`,
    `    Header set Cache-Control "public, max-age=${assetMaxAge}"`,
    "  </FilesMatch>",
    "</IfModule>"
  ].join("\n");
}

function buildCorsSection(state: HtaccessGeneratorState) {
  const origins = splitValues(state.corsOrigins);

  if (!origins.length) {
    return "";
  }

  if (origins.includes("*")) {
    return ["<IfModule mod_headers.c>", "  Header set Access-Control-Allow-Origin \"*\"", "</IfModule>"].join("\n");
  }

  return [
    "<IfModule mod_headers.c>",
    `  SetEnvIfNoCase Origin "^(${origins.map(escapeRegex).join("|")})$" ORIGIN_ALLOWED=$0`,
    "  Header set Access-Control-Allow-Origin \"%{ORIGIN_ALLOWED}e\" env=ORIGIN_ALLOWED",
    "  Header set Vary \"Origin\" env=ORIGIN_ALLOWED",
    "</IfModule>"
  ].join("\n");
}

function normalizePath(path: string) {
  const trimmed = path.trim();
  return trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
}

function splitValues(value: string) {
  return value
    .split(/\s+/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function escapeRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/^https?:\/\//, "https?://");
}

function escapeRewriteDomain(value: string) {
  return value.replace(/^https?:\/\//, "").replace(/\/.*$/, "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
